name: Cypress Test Runs
on: push

jobs:
    init:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install node
              uses: actions/setup-node@v4  
              with:
                node-version: '22'
            - name: Install Deps
              run: npm ci         
            - uses: bissolli/gh-action-persist-workspace@v2
              with:
                action: persist
    test1:
        needs: [init]
        runs-on: ubuntu-latest
        steps:
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            - uses: bissolli/gh-action-persist-workspace@v2
              with:
                action: retrieve
            - name: Cypress run Test1
              uses: cypress-io/github-action@v6
              with:
                spec: cypress/specs/myTest.spec.js
              
    test2:
        needs: [init]
        runs-on: ubuntu-latest
        steps:
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            - uses: bissolli/gh-action-persist-workspace@v2
              with:
                action: retrieve
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                spec: cypress/specs/test.spec.js  