name: Cypress Test Runs
on: workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Welcome to Cypress Test"
      - name: Print Bye
        run: echo "Bye.. Bye..."
