name: Cypress Test Runs
on: push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4  
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm ci         
      - uses: bissolli/gh-action-persist-workspace@v2
        with:
          action: persist

  test:
    needs: [init]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_folders:
          - 'cypress/specs/test1/myTest.spec.js'
          - 'cypress/specs/test2/test.spec.js'
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: bissolli/gh-action-persist-workspace@v2
        with:
          action: retrieve
      - name: List Spec Directories
        run: ls -R cypress/specs/
      - name: Cypress Run Test
        uses: cypress-io/github-action@v6
        with:
          start: npm run # Change this based on your needs
          browser: chrome
          spec: ${{ matrix.spec_folders }}
