name: Cypress Test Runs
on: push

jobs:
    init:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install node
              uses: actions/setup-node@v4  
              with:
                node-version: '22'
            - name: Install Deps
              run: npm ci         
            - uses: bissolli/gh-action-persist-workspace@v2
              with:
                action: persist
    test1:
        needs: [init]
        runs-on: ubuntu-latest
        strategy:
            matrix:
                spec_folders:
                   - 'cypress/specs/test1/*.spec.js'
                   - 'cypress/specs/test2/*.spec.js'
        steps:
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            - uses: bissolli/gh-action-persist-workspace@v2
              with:
                action: retrieve
            - name: Cypress run Test1
              uses: cypress-io/github-action@v6
              with:
                start: npm run
                browser: chrome
                tag: ${{ matrix.spec_folders }}
                spec: ${{ matrix.spec_folders }}
